# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def commonPods
  pod 'ReactiveObjC'
  pod 'MJExtension', '3.2.2'
  pod 'Toast', '~> 4.0.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'XLForm', '~> 4.3'
  pod 'CocoaLumberjack'
  pod 'Masonry'
  pod 'Bugly'
  pod 'MJRefresh', '3.7.2'
  pod 'SDWebImage', '5.12.1'
end


target 'WindmillSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  #  use_frameworks!
  
  
  # Pods for WindmillSample
  commonPods
  pod 'WindmillAd-iOS', '1.4.3', :subspecs => [   #Mintegral
      'TouTiaoAdapter',
      'AdmobAdapter',
      'AppLovinAdapter',
      'MintegralAdapter',
      'GDTAdapter',
      'IronSourceAdapter',
      'VungleAdapter',
      'UnityAdsAdapter',
      'KSAdapter',
      'BaiduAdapter',
      'KlevinAdapter',
  ]
end
